// <auto-generated />
using System;
using Gestor_De_Pule.src.Persistencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestor_De_Pule.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20251021021314_AddNullToAnimalListAndApostador")]
    partial class AddNullToAnimalListAndApostador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AnimalPule", b =>
                {
                    b.Property<int>("AnimaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PulesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimaisId", "PulesId");

                    b.HasIndex("PulesId");

                    b.ToTable("AnimalPule");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jockey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Número")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Proprietário")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Treinador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Apostador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apostadors");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Pule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApostadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorId");

                    b.ToTable("Pules");
                });

            modelBuilder.Entity("AnimalPule", b =>
                {
                    b.HasOne("Gestor_De_Pule.src.Model.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestor_De_Pule.src.Model.Pule", null)
                        .WithMany()
                        .HasForeignKey("PulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Pule", b =>
                {
                    b.HasOne("Gestor_De_Pule.src.Model.Apostador", "Apostador")
                        .WithMany("Pules")
                        .HasForeignKey("ApostadorId");

                    b.Navigation("Apostador");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Apostador", b =>
                {
                    b.Navigation("Pules");
                });
#pragma warning restore 612, 618
        }
    }
}
