// <auto-generated />
using System;
using Gestor_De_Pule.src.Persistencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestor_De_Pule.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20260104013912_ResultadoDisputaAnimal")]
    partial class ResultadoDisputaAnimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AnimalPule", b =>
                {
                    b.Property<int>("AnimaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PulesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimaisId", "PulesId");

                    b.HasIndex("PulesId");

                    b.ToTable("AnimalPule");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jockey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Número")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Proprietário")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Treinador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Apostador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apostadors");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Pule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApostadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisputaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Número")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorId");

                    b.HasIndex("DisputaId");

                    b.ToTable("Pules");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Taxa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Disputa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.ToTable("Disputas");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisputaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Posição")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Tempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DisputaId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("AnimalPule", b =>
                {
                    b.HasOne("Gestor_De_Pule.src.Model.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestor_De_Pule.src.Model.Pule", null)
                        .WithMany()
                        .HasForeignKey("PulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Pule", b =>
                {
                    b.HasOne("Gestor_De_Pule.src.Model.Apostador", "Apostador")
                        .WithMany("Pules")
                        .HasForeignKey("ApostadorId");

                    b.HasOne("Gestor_De_Pule.src.Models.Disputa", "Disputa")
                        .WithMany("Pules")
                        .HasForeignKey("DisputaId");

                    b.Navigation("Apostador");

                    b.Navigation("Disputa");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Disputa", b =>
                {
                    b.HasOne("Gestor_De_Pule.src.Models.Caixa", "Caixa")
                        .WithMany("Disputs")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caixa");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Resultado", b =>
                {
                    b.HasOne("Gestor_De_Pule.src.Model.Animal", "Animal")
                        .WithMany("Resultados")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestor_De_Pule.src.Models.Disputa", "Disputa")
                        .WithMany("ResultadoList")
                        .HasForeignKey("DisputaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Disputa");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Animal", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Model.Apostador", b =>
                {
                    b.Navigation("Pules");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Caixa", b =>
                {
                    b.Navigation("Disputs");
                });

            modelBuilder.Entity("Gestor_De_Pule.src.Models.Disputa", b =>
                {
                    b.Navigation("Pules");

                    b.Navigation("ResultadoList");
                });
#pragma warning restore 612, 618
        }
    }
}
